version: "3.8"
services:
  webserver:
    image: nginx:latest
    container_name: bootstrap_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bootstrap_network
networks:
  bootstrap_network:
    driver: bridge
