services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brewease_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    command: npm run dev -- --host 0.0.0.0
    networks:
      - brewease_network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: brewease_backend_dev
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=2001
      - DB_NAME=BrewDB
      - PORT=5000
      - JWT_SECRET=asAfhjJASV1JS6k82GSIajsbfuAJ8tKJ7tiu
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - brewease_network

  db:
    image: postgres:15
    container_name: brewease_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2001
      POSTGRES_DB: BrewDB
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - brewease_network

networks:
  brewease_network:
    driver: bridge

volumes:
  db_data_dev:
