version: "3.8"
services:
  webserver:
    image: nginx:latest
    container_name: brewease_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - brewease_network

  backend:
    build: ./backend # Use the Dockerfile in the backend directory
    container_name: brewease_backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app # Mount the backend directory for development (optional)
      - /app/node_modules # Ensure node_modules is not overwritten by the volume
    networks:
      - brewease_network
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: BrewDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2001
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - brewease_network

networks:
  brewease_network:
    driver: bridge
